name: Deploy

on:
  push:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v2

      - name: Setup Node.js

        uses: actions/setup-node@v2-beta

        with:

          node-version: '18'

          check-latest: true

      - name: Install NPM dependencies

        run: npm install --force

      - name: Compile assets for production

        run: npm run build

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.VPS_IP }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: "."
          target: "/var/www/html/staging.aqebbd.com"

      - name: Executing remote command
        uses: boy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: 'cd /var/www/html/staging.aqebbd.com && sudo -S chmod 777 server_deploy.sh && ./server_deploy.sh'
          # script: 'sudo chown -R www-data.www-data /var/www/html/aqebbd.com/bootstrap/cache/'

